// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FinFunSharp")>]
[<assembly: AssemblyProductAttribute("FinFunSharp")>]
[<assembly: AssemblyDescriptionAttribute("Financial playground in F#")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FinFunSharp"
    let [<Literal>] AssemblyProduct = "FinFunSharp"
    let [<Literal>] AssemblyDescription = "Financial playground in F#"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
